server:
  port: 8082
  servlet:
    context-path: "/user-service"
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
#    TODO :  configure MySql Database
spring:
  h2:
    #h2 console url: http://localhost:8082/user-service/h2-console
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver