desired_count: 2
path: "/"
container_port: 25050
container_cpu: 2048
container_memory: 4096
alb_scheme: internal
health_check_path: "/actuator/info"
container_environment:
- name: DP_SSM_KEYS
  value: >-
    {
      "region": "ap-south-1",
      "prefixed_keys": [
        {
          "prefix": "/conf/{{ DP_SERVICE_NAME }}/{{ DP_RUN_ENV }}",
          "region": "ap-south-1",
          "keys": {
            "v1/DB_HOST": {},
            "v1/DB_NAME": {},
            "v1/DB_PORT": {},
            "v1/DB_USER": {},
            "v1/DB_PASSWORD": {}
          }
        }
      ]
    }